### ISSUE TITLE
Compiling with a non-default providerDirectory fails

### ISSUE THREAD

**Issue by stoltene2** [meoblast001/hakyll-sass#10]
When using a non-default `providerDirectory` such as `site` the following error is thrown during site compilation. I tracked this down to the code just using the file path of the identifier which is already relative to the `providerDirectory`.

```
Initialising...
  Creating store...
  Creating provider...
  Running rules...
Checking for out-of-date items
Compiling
  updated templates/archive.html
  updated templates/post-list.html
  updated templates/default.html
  updated templates/navbar.html
  updated templates/footer.html
  updated archive
  updated atom.xml
  updated css/bootstrap.css
  updated css/bootstrap.min.css
  [ERROR] user error (Internal Error: File to read not found or unreadable: css/default.sass
```

**Comment by KyleOndy** [comment]
@meoblast001, Do you have any plans of fixing this issue or plans on merging #11?

**Comment by meoblast001** [comment]
Sorry for neglecting this issue. I haven't been doing much with this project lately. I just merged this into develop and will try to get it on hackage soon.

**Comment by KyleOndy** [comment]
Thanks!

I've got a local fork I've been using, I'll be opening some PRs in the next days with some changes I've made.
