### ISSUE TITLE
Uploading to stackage?

### ISSUE THREAD

**Issue by mstksg** [meoblast001/hakyll-sass#4]
Hi!  Thanks for the great package, it's been very useful to me! :)

Just wondering if there any plans to put hakyll-sass onto the [stackage](https://www.stackage.org/) package database?

(If you wanted to, it's as simple as [editing this file](https://github.com/fpco/stackage/edit/master/build-constraints.yaml))

**Comment by meoblast001** [comment]
Thanks. I will take a look into this and put it on Stackage soon. :)

**Comment by meoblast001** [comment]
This issue will be closed when this PR on Stackage is merged.
https://github.com/fpco/stackage/pull/1378
