### ISSUE TITLE
Getting Started/Examples

### ISSUE THREAD

**Issue by ethagnawl** [meoblast001/hakyll-sass#5]
First off, thank you for putting this library together! With a little help (courtesy of some of your other projects), I was able to integrate hakyll-sass into my project and it's working nicely. 

Would you be open to accepting a Pull Request which would add some instructions and/or examples to the README?

**Comment by meoblast001** [comment]
Thank you for your thanks :).. or shall I say you're welcome. I would definitely be open to a PR with examples in the README. I may even try to add some myself but I'm a bit busy in the next month so maybe you'll beat me to it.

**Comment by ethagnawl** [comment]
@meoblast001 Please see PR #6.

**Comment by meoblast001** [comment]
Thanks @ethagnawl. I just merged your PR.
