### ISSUE TITLE
stack build error

### ISSUE THREAD

**Issue by ygpark2** [meoblast001/hakyll-sass#8]
![2016-11-28 10 13 50](https://cloud.githubusercontent.com/assets/93011/20653608/7024e530-b553-11e6-9f16-ac15b54df184.png)

As you can see on the captured image,  aeson-pretty is also depending on pandoc-citeproc library but the problem is these two different libraries seem to require a different version of aeson-pretty.

Do you know how to fix this error? or did I understanding something wrong?

**Comment by cyrbon** [comment]
There is a typo in `.cabal file`. Instead of ` , aeson-pretty < 0.8` it should be ` , aeson-pretty >= 0.8`. I have tested it and it works.

**Comment by meoblast001** [comment]
Thanks. I applied that change last night to a new branch and it passed builds in CI. I'll try to merge and release a bug fix release soon.

**Comment by meoblast001** [comment]
I released an update. @ygpark2 could you test your example against the new release and let me know if it's solved?

**Comment by ygpark2** [comment]
@meoblast001  
The new release seem to work very smoothly. I confirm that your new release surely resolve my issue.
I do appreciate your effort to integrate sass compiler into hakyll project.
Thank you.

**Comment by meoblast001** [comment]
Thanks for finding and helping with this bug :).
